### ISSUE TITLE
Desktop Webview not working with latest Compose 1.12

### ISSUE THREAD

**Issue by maicol07** [parkwoocheol/compose-webview#63]
Hi,
webview on desktop crashes while using Compose 1.12. Exception:
```
java.lang.NoSuchMethodError: 'void androidx.compose.ui.awt.SwingPanel_desktopKt.SwingPanel-euL9pac(long, kotlin.jvm.functions.Function0, androidx.compose.ui.Modifier, kotlin.jvm.functions.Function1, androidx.compose.runtime.Composer, int, int)'
	at com.parkwoocheol.composewebview.ComposeWebView_desktopKt.ComposeWebViewImpl(ComposeWebView.desktop.kt:324)
	at com.parkwoocheol.composewebview.ComposeWebViewKt.ComposeWebView(ComposeWebView.kt:159)
	at it.maicol07.gamerlogue.ui.components.ServiceWebViewKt.rememberServiceWebViewHost$lambda$7(ServiceWebView.kt:147)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:131)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
	at it.maicol07.gamerlogue.ui.views.settings.categories.ServiceSyncScreenKt.ServiceSyncScreen$lambda$11(ServiceSyncScreen.kt:145)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:131)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:52)
```

**Comment by parkwoocheol** [comment]
Thanks for the report — fixed in #64, now on `main`.

### Root cause

Compose Multiplatform 1.12 changed `SwingPanel`'s deprecated `background` parameter from `Color` to
`Color?`. That flips the value-class parameter from `long` to a boxed `Color`, so the Kotlin
mangling hash changes, and a new overload without `background` was added alongside it:

| Compose | symbols exposed by `SwingPanel_desktopKt` |
| --- | --- |
| 1.9.3 – 1.11.1 | `SwingPanel-euL9pac(long, Function0, Modifier, Function1, Composer, int, int)` |
| 1.12.0-beta* | `SwingPanel(Function0, Modifier, Function1, Composer, int, int)`<br>`SwingPanel-iRkQZW0(Color, Function0, Modifier, Function1, Composer, int, int)` |

The symbol this library was compiled against no longer exists, which is the `NoSuchMethodError` you
hit. Scanning every Compose reference in the desktop jar, `SwingPanel` is the only affected one —
everything else is compiler-generated runtime API that stayed compatible.

Since both 1.12 overloads are absent from ≤ 1.11 and the ≤ 1.11 symbol is absent from 1.12, no
single compiled call site satisfies both.

### Fix

Compose 1.9.3 – 1.11.x keep the existing direct call, so nothing changes for them. On 1.12+ the
overload that is actually present is resolved once and invoked reflectively. There is no
minimum-Compose bump — the supported range stays 1.9.3+.

Verified by running a shim compiled against Compose 1.9.3 in a real desktop window on each runtime,
driving recompositions plus a remove/re-add cycle:

| Compose runtime | before | after |
| --- | --- | --- |
| 1.9.3 / 1.10.3 / 1.11.1 | pass | pass |
| 1.12.0-beta01 / 1.12.0-beta03 | **reproduces your stack trace** | pass |

It will go out in the next release; until then you can build from `main`.

### Upstream note

This looks unintended on the Compose side: the `background` parameter was deprecated for *source*
compatibility, but switching it to `Color?` silently renamed the JVM symbol and broke *binary*
compatibility for anything compiled against 1.11 or earlier. 1.12 is still in beta, so it may be
worth raising on YouTrack. Either way this fix is safe — if the old symbol returns, the direct call
path is simply used again.
